### ISSUE TITLE
reCaptcha reset

### ISSUE THREAD

**Issue by danieljausovec** [slushie/recaptcha-secure-token#3] opened 2015-08-07 12:45 UTC
Hi.

reCaptcha after jQuery reset no longer work.
I get "Bad request" from google.

Example:
grecaptcha.reset();

**Comment by slushie** [comment] 2015-08-07 17:58
I cannot reproduce this issue on my own. However, the ReCaptcha stoken has a built-in timestamp value. It's possible that you are calling "reset" with an expired stoken. You should re-generate your stoken before calling "reset."

I'm going to close the issue for now, unless you can provide repeatable steps to reproduce.

**Closed as completed by slushie** 2015-08-07 17:58 UTC
